openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/schools:
    get:
      summary: 'Display a listing of the school in Surabaya.'
      operationId: displayAListingOfTheSchoolInSurabaya
      description: ''
      parameters:
        -
          in: header
          name: Api-Key
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: success
                  data:
                    -
                      id: 1
                      name: 'sekolah citra berkat'
                      address: wadaw
                      postal_code: 22312
                      school_type: SD
                      phone_number: 2131231231
                    -
                      id: 2
                      name: 'sekolah citra berkat'
                      address: wadaw
                      postal_code: 22312
                      school_type: SMP
                      phone_number: 2131231231
                    -
                      id: 3
                      name: 'sekolah citra berkat'
                      address: wadaw
                      postal_code: 22312
                      school_type: SMA
                      phone_number: 2131231231
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: success
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: 'sekolah citra berkat'
                        address: wadaw
                        postal_code: 22312
                        school_type: SD
                        phone_number: 2131231231
                      -
                        id: 2
                        name: 'sekolah citra berkat'
                        address: wadaw
                        postal_code: 22312
                        school_type: SMP
                        phone_number: 2131231231
                      -
                        id: 3
                        name: 'sekolah citra berkat'
                        address: wadaw
                        postal_code: 22312
                        school_type: SMA
                        phone_number: 2131231231
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: 'sekolah citra berkat'
                        address:
                          type: string
                          example: wadaw
                        postal_code:
                          type: integer
                          example: 22312
                        school_type:
                          type: string
                          example: SD
                        phone_number:
                          type: integer
                          example: 2131231231
      tags:
        - 'All Surabaya School'
  '/api/schools/name/{name}':
    get:
      summary: 'Display the specified school in surabaya by name.'
      operationId: displayTheSpecifiedSchoolInSurabayaByName
      description: ''
      parameters:
        -
          in: header
          name: Api-Key
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: success
                  data:
                    id: 1
                    name: 'sekolah citra berkat'
                    address: wadaw
                    postal_code: 22312
                    school_type: SD
                    phone_number: 2131231231
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'sekolah citra berkat'
                      address:
                        type: string
                        example: wadaw
                      postal_code:
                        type: integer
                        example: 22312
                      school_type:
                        type: string
                        example: SD
                      phone_number:
                        type: integer
                        example: 2131231231
      tags:
        - 'All Surabaya School'
    parameters:
      -
        in: path
        name: name
        description: 'The school name.'
        example: 'sekolah citra berkat'
        required: true
        schema:
          type: string
  '/api/schools/postal/{postal_code}':
    get:
      summary: 'Display the specified school in surabaya by postal code.'
      operationId: displayTheSpecifiedSchoolInSurabayaByPostalCode
      description: ''
      parameters:
        -
          in: header
          name: Api-Key
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: success
                  data:
                    id: 1
                    name: 'sekolah citra berkat'
                    address: wadaw
                    postal_code: 22312
                    school_type: SD
                    phone_number: 2131231231
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'sekolah citra berkat'
                      address:
                        type: string
                        example: wadaw
                      postal_code:
                        type: integer
                        example: 22312
                      school_type:
                        type: string
                        example: SD
                      phone_number:
                        type: integer
                        example: 2131231231
      tags:
        - 'All Surabaya School'
    parameters:
      -
        in: path
        name: postal_code
        description: 'The school name.'
        example: 22312
        required: true
        schema:
          type: integer
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/schools/elementary:
    get:
      summary: 'Display all of elementary school in surabaya.'
      operationId: displayAllOfElementarySchoolInSurabaya
      description: ''
      parameters:
        -
          in: header
          name: Api-Key
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: success
                  data:
                    -
                      id: 1
                      name: 'sekolah citra berkat'
                      address: wadaw
                      postal_code: 22312
                      school_type: SD
                      phone_number: 2131231231
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: success
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: 'sekolah citra berkat'
                        address: wadaw
                        postal_code: 22312
                        school_type: SD
                        phone_number: 2131231231
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: 'sekolah citra berkat'
                        address:
                          type: string
                          example: wadaw
                        postal_code:
                          type: integer
                          example: 22312
                        school_type:
                          type: string
                          example: SD
                        phone_number:
                          type: integer
                          example: 2131231231
      tags:
        - 'Surabaya Elementary School'
  '/api/schools/elementary/{name}':
    get:
      summary: 'Display the specified school in surabaya by name.'
      operationId: displayTheSpecifiedSchoolInSurabayaByName
      description: ''
      parameters:
        -
          in: header
          name: Api-Key
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: success
                  data:
                    id: 1
                    name: 'sekolah citra berkat'
                    address: wadaw
                    postal_code: 22312
                    school_type: SD
                    phone_number: 2131231231
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'sekolah citra berkat'
                      address:
                        type: string
                        example: wadaw
                      postal_code:
                        type: integer
                        example: 22312
                      school_type:
                        type: string
                        example: SD
                      phone_number:
                        type: integer
                        example: 2131231231
      tags:
        - 'Surabaya Elementary School'
    parameters:
      -
        in: path
        name: name
        description: 'The school name.'
        example: 'sekolah citra berkat'
        required: true
        schema:
          type: string
  '/api/schools/elementary/{postal_code}':
    get:
      summary: 'Display the specified school in surabaya by postal code.'
      operationId: displayTheSpecifiedSchoolInSurabayaByPostalCode
      description: ''
      parameters:
        -
          in: header
          name: Api-Key
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: success
                  data: null
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: success
                  data:
                    type: string
                    example: null
      tags:
        - 'Surabaya Elementary School'
    parameters:
      -
        in: path
        name: postal_code
        description: 'The school name.'
        example: 22312
        required: true
        schema:
          type: integer
  /api/schools/junior:
    get:
      summary: 'Display all of junior high school in surabaya.'
      operationId: displayAllOfJuniorHighSchoolInSurabaya
      description: ''
      parameters:
        -
          in: header
          name: Api-Key
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: success
                  data:
                    -
                      id: 2
                      name: 'sekolah citra berkat'
                      address: wadaw
                      postal_code: 22312
                      school_type: SMP
                      phone_number: 2131231231
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: success
                  data:
                    type: array
                    example:
                      -
                        id: 2
                        name: 'sekolah citra berkat'
                        address: wadaw
                        postal_code: 22312
                        school_type: SMP
                        phone_number: 2131231231
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 2
                        name:
                          type: string
                          example: 'sekolah citra berkat'
                        address:
                          type: string
                          example: wadaw
                        postal_code:
                          type: integer
                          example: 22312
                        school_type:
                          type: string
                          example: SMP
                        phone_number:
                          type: integer
                          example: 2131231231
      tags:
        - 'Surabaya Junior High School'
  '/api/schools/junior/{name}':
    get:
      summary: 'Display the specified school in surabaya by name.'
      operationId: displayTheSpecifiedSchoolInSurabayaByName
      description: ''
      parameters:
        -
          in: header
          name: Api-Key
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: success
                  data:
                    id: 2
                    name: 'sekolah citra berkat'
                    address: wadaw
                    postal_code: 22312
                    school_type: SMP
                    phone_number: 2131231231
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 2
                      name:
                        type: string
                        example: 'sekolah citra berkat'
                      address:
                        type: string
                        example: wadaw
                      postal_code:
                        type: integer
                        example: 22312
                      school_type:
                        type: string
                        example: SMP
                      phone_number:
                        type: integer
                        example: 2131231231
      tags:
        - 'Surabaya Junior High School'
    parameters:
      -
        in: path
        name: name
        description: 'The school name.'
        example: 'sekolah citra berkat'
        required: true
        schema:
          type: string
  '/api/schools/junior/{postal_code}':
    get:
      summary: 'Display the specified school in surabaya by postal code.'
      operationId: displayTheSpecifiedSchoolInSurabayaByPostalCode
      description: ''
      parameters:
        -
          in: header
          name: Api-Key
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: success
                  data: null
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: success
                  data:
                    type: string
                    example: null
      tags:
        - 'Surabaya Junior High School'
    parameters:
      -
        in: path
        name: postal_code
        description: 'The school name.'
        example: 22312
        required: true
        schema:
          type: integer
  /api/schools/senior:
    get:
      summary: 'Display all of Senior High School in surabaya.'
      operationId: displayAllOfSeniorHighSchoolInSurabaya
      description: ''
      parameters:
        -
          in: header
          name: Api-Key
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: success
                  data:
                    -
                      id: 3
                      name: 'sekolah citra berkat'
                      address: wadaw
                      postal_code: 22312
                      school_type: SMA
                      phone_number: 2131231231
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: success
                  data:
                    type: array
                    example:
                      -
                        id: 3
                        name: 'sekolah citra berkat'
                        address: wadaw
                        postal_code: 22312
                        school_type: SMA
                        phone_number: 2131231231
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 3
                        name:
                          type: string
                          example: 'sekolah citra berkat'
                        address:
                          type: string
                          example: wadaw
                        postal_code:
                          type: integer
                          example: 22312
                        school_type:
                          type: string
                          example: SMA
                        phone_number:
                          type: integer
                          example: 2131231231
      tags:
        - 'Surabaya Senior High School'
  '/api/schools/senior/{name}':
    get:
      summary: 'Display the specified school in surabaya by name.'
      operationId: displayTheSpecifiedSchoolInSurabayaByName
      description: ''
      parameters:
        -
          in: header
          name: Api-Key
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: success
                  data:
                    id: 3
                    name: 'sekolah citra berkat'
                    address: wadaw
                    postal_code: 22312
                    school_type: SMA
                    phone_number: 2131231231
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 3
                      name:
                        type: string
                        example: 'sekolah citra berkat'
                      address:
                        type: string
                        example: wadaw
                      postal_code:
                        type: integer
                        example: 22312
                      school_type:
                        type: string
                        example: SMA
                      phone_number:
                        type: integer
                        example: 2131231231
      tags:
        - 'Surabaya Senior High School'
    parameters:
      -
        in: path
        name: name
        description: 'The school name.'
        example: 'sekolah citra berkat'
        required: true
        schema:
          type: string
  '/api/schools/senior/{postal_code}':
    get:
      summary: 'Display the specified school in surabaya by postal code.'
      operationId: displayTheSpecifiedSchoolInSurabayaByPostalCode
      description: ''
      parameters:
        -
          in: header
          name: Api-Key
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: success
                  data: null
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: success
                  data:
                    type: string
                    example: null
      tags:
        - 'Surabaya Senior High School'
    parameters:
      -
        in: path
        name: postal_code
        description: 'The school name.'
        example: 22312
        required: true
        schema:
          type: integer
tags:
  -
    name: 'All Surabaya School'
    description: ''
  -
    name: Endpoints
    description: ''
  -
    name: 'Surabaya Elementary School'
    description: ''
  -
    name: 'Surabaya Junior High School'
    description: ''
  -
    name: 'Surabaya Senior High School'
    description: ''
components:
  securitySchemes:
    default:
      type: apiKey
      name: Api-Key
      in: header
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
